# Generated by Django 5.1.4 on 2024-12-17 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Код самолета, IATA')),
                ('model', models.TextField(verbose_name='Модель самолета')),
                ('range', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальная дальность полета,км')),
            ],
            options={
                'verbose_name': 'Самолёт',
                'verbose_name_plural': 'Самолёты',
                'ordering': ['range'],
                'default_related_name': 'aircrafts',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=4)),
                ('fare_conditions', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('buisness', 'Buisness')], max_length=10)),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aircraft', verbose_name='Код самолета, IATA')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['aircraft_code'],
                'default_related_name': 'seats',
            },
        ),
    ]
