# Generated by Django 5.1.4 on 2024-12-15 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Код самолета, IATA')),
                ('model', models.TextField(verbose_name='Модель самолета')),
                ('range', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальная дальность полета,км')),
            ],
        ),
    ]
