# Generated by Django 5.1.4 on 2024-12-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'default_related_name': 'aircrafts', 'ordering': ('model',), 'verbose_name': 'Самолёт', 'verbose_name_plural': 'Самолёты'},
        ),
    ]
