# Generated by Django 5.1.4 on 2024-12-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aircraft_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'default_related_name': 'aircrafts', 'ordering': (models.OrderBy(models.F('model'), nulls_last=True),), 'verbose_name': 'Самолёт', 'verbose_name_plural': 'Самолёты'},
        ),
    ]
